[package]
name = "beanputter-htmx"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
csv = "1.3.1"
either = "1.15.0"
askama = {version = "0.14", features = ["code-in-doc"]}
askama_web = {version = "0.14", features = ["axum-0.8"]}
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = [ "full" ] }
