[package]
name = "beanputter-htmx"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
csv = "1.3.1"
maud = { version = "0.27.0", features = [ "axum" ] }
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = [ "full" ] }
